apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  labels:
    app: redis-cluster
spec:
  ports:
  - port: 6379
    name: rest
    protocol: TCP
  - port: 16379
    name: gossip
    protocol: TCP
  selector:
  app: redis-cluster